In [2]:
import numpy as np
a=np.arange(52)
b=np.arange(86)
print(b)
a = np.arange(42).reshape(7,6)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]]


In [3]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(7, 6)
42
int32
4
<class 'numpy.ndarray'>


In [4]:
b=np.array([1.0, 3.0, 5.0, 7.0])
print(b)
print(b.dtype)
print(type(b))

[1. 3. 5. 7.]
float64
<class 'numpy.ndarray'>


In [5]:
c=np.eye(18)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0

In [6]:
d=np.linspace(-1, 8, 16, endpoint=True)
d

array([-1. , -0.4,  0.2,  0.8,  1.4,  2. ,  2.6,  3.2,  3.8,  4.4,  5. ,
        5.6,  6.2,  6.8,  7.4,  8. ])

In [7]:
f=np.logspace(-1, 8, 17, endpoint=True, base=10)
f

array([1.00000000e-01, 3.65174127e-01, 1.33352143e+00, 4.86967525e+00,
       1.77827941e+01, 6.49381632e+01, 2.37137371e+02, 8.65964323e+02,
       3.16227766e+03, 1.15478198e+04, 4.21696503e+04, 1.53992653e+05,
       5.62341325e+05, 2.05352503e+06, 7.49894209e+06, 2.73841963e+07,
       1.00000000e+08])

In [8]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [9]:
g=np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)
g

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [10]:
a=np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [11]:
a*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [12]:
a+a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [13]:
a*a

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289]])

In [14]:
c=a.transpose()
c

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [15]:
a @ c

array([[  5,  14,  23,  32,  41,  50],
       [ 14,  50,  86, 122, 158, 194],
       [ 23,  86, 149, 212, 275, 338],
       [ 32, 122, 212, 302, 392, 482],
       [ 41, 158, 275, 392, 509, 626],
       [ 50, 194, 338, 482, 626, 770]])

In [16]:
print(a)
a.sum(axis=1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


array([ 3, 12, 21, 30, 39, 48])

In [17]:
a.sum()

153

In [18]:
print(a.min(),a.max())

0 17


In [19]:
b=a*np.pi/6.5
b

array([[0.        , 0.48332195, 0.96664389],
       [1.44996584, 1.93328779, 2.41660973],
       [2.89993168, 3.38325363, 3.86657557],
       [4.34989752, 4.83321947, 5.31654141],
       [5.79986336, 6.28318531, 6.76650725],
       [7.2498292 , 7.73315115, 8.21647309]])

In [20]:
c=np.cos(b)
c

array([[ 1.        ,  0.88545603,  0.56806475],
       [ 0.12053668, -0.35460489, -0.74851075],
       [-0.97094182, -0.97094182, -0.74851075],
       [-0.35460489,  0.12053668,  0.56806475],
       [ 0.88545603,  1.        ,  0.88545603],
       [ 0.56806475,  0.12053668, -0.35460489]])

In [21]:
d=b+c
print(d)

[[1.         1.36877797 1.53470864]
 [1.57050252 1.5786829  1.66809899]
 [1.92898986 2.41231181 3.11806483]
 [3.99529263 4.95375615 5.88460616]
 [6.68531939 7.28318531 7.65196328]
 [7.81789395 7.85368783 7.86186821]]


In [22]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
n=int(input("n"))
num=np.arange(n)
num
even=num[0:151:2]
even

n150


array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148])

In [24]:
a[3]

3

In [25]:
print(a[4:5])

[4]


In [26]:
a[3:7]

array([3, 4, 5, 6])

In [27]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
x=np.arange(18).reshape(3,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [29]:
x[1,3]

9

In [30]:
x[0:2,0:2]

array([[0, 1],
       [6, 7]])

In [31]:
x[:,5]

array([ 5, 11, 17])

In [32]:
x=x.flatten()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [33]:
#print (a)
for sandy in x:
    print(sandy)
x=np.arange(18).reshape(3,6)
x

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [34]:
for e in x.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [35]:
for e in x.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [37]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
b=a*2
b is a

False

In [39]:
b.shape=(4,6)
print(b)
a.shape

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]


(24,)

In [40]:
b is a

False

In [41]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [42]:
a=np.arange(12)
c=a[:]
a.shape=(3,4)

print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [43]:
c[5]= -1
print(a)
print(c)

[[ 0  1  2  3]
 [ 4 -1  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4 -1  6  7  8  9 10 11]


In [44]:
d=c[3:8]
d

array([ 3,  4, -1,  6,  7])

In [45]:
d[:]

array([ 3,  4, -1,  6,  7])

In [46]:
print(a)
print(c)
print(d)

[[ 0  1  2  3]
 [ 4 -1  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4 -1  6  7  8  9 10 11]
[ 3  4 -1  6  7]


In [47]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [48]:
d=a.copy()
d[:,:]=0.0

print(a)
print(d)

[[ 0  1  2  3]
 [ 4 -1  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [49]:
import numpy as np
h = np.arange(12).reshape(3,4)
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
h[h > 4] = 0
h

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
h[h==0]=-1
h

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [52]:
h==-1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
h=np.arange(12).reshape(4,3)
h[np.logical_and(h>3, h<=9)]=0.0
print(h)

[[ 0  1  2]
 [ 3  0  0]
 [ 0  0  0]
 [ 0 10 11]]


In [54]:
h>4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [55]:
X=24
Y=48

xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, X, endpoint=False)
y = np.linspace(ymin, ymax, Y, endpoint=False)

print(x.shape)
print(y.shape)
y

(24,)
(48,)


array([0.        , 0.02083333, 0.04166667, 0.0625    , 0.08333333,
       0.10416667, 0.125     , 0.14583333, 0.16666667, 0.1875    ,
       0.20833333, 0.22916667, 0.25      , 0.27083333, 0.29166667,
       0.3125    , 0.33333333, 0.35416667, 0.375     , 0.39583333,
       0.41666667, 0.4375    , 0.45833333, 0.47916667, 0.5       ,
       0.52083333, 0.54166667, 0.5625    , 0.58333333, 0.60416667,
       0.625     , 0.64583333, 0.66666667, 0.6875    , 0.70833333,
       0.72916667, 0.75      , 0.77083333, 0.79166667, 0.8125    ,
       0.83333333, 0.85416667, 0.875     , 0.89583333, 0.91666667,
       0.9375    , 0.95833333, 0.97916667])

In [56]:
import time
import numpy as np
X=24
Y=42
x=np.linspace(0.0, 1.0, X, endpoint=False)
y=np.linspace(0.0, 1.0, Y, endpoint=False)


In [57]:
t0=time.time()

g=np.zeros((X,Y))
for i in range(X):
    for j in range(Y):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
        
t1=time.time()
print("time elapsed: {} s".format(t1-t0))
print(g)

time elapsed: 0.004424571990966797 s
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00623328  0.01246631 ...  0.24071208  0.2467574
   0.25279313]
 [ 0.          0.01246631  0.02493069 ...  0.46726863  0.47825398
   0.489165  ]
 ...
 [ 0.          0.13052619  0.25881905 ... -0.92387953 -0.8660254
  -0.79335334]
 [ 0.          0.13670361  0.27084047 ... -0.80459778 -0.71586685
  -0.61369479]
 [ 0.          0.14287571  0.2828198  ... -0.63800015 -0.5214352
  -0.39417107]]


In [58]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.02380952 0.04761905 0.07142857 0.0952381  0.11904762
 0.14285714 0.16666667 0.19047619 0.21428571 0.23809524 0.26190476
 0.28571429 0.30952381 0.33333333 0.35714286 0.38095238 0.4047619
 0.42857143 0.45238095 0.47619048 0.5        0.52380952 0.54761905
 0.57142857 0.5952381  0.61904762 0.64285714 0.66666667 0.69047619
 0.71428571 0.73809524 0.76190476 0.78571429 0.80952381 0.83333333
 0.85714286 0.88095238 0.9047619  0.92857143 0.95238095 0.97619048]


In [59]:
t = time.time()
g2= np.sin(2.0*np.pi*x2d*y2d)
t1=time.time()
print("time elapsed: {} s".format(t1-t0))
print(x2d)

time elapsed: 20.750867128372192 s
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.04166667 0.04166667 0.04166667 ... 0.04166667 0.04166667 0.04166667]
 [0.08333333 0.08333333 0.08333333 ... 0.08333333 0.08333333 0.08333333]
 ...
 [0.875      0.875      0.875      ... 0.875      0.875      0.875     ]
 [0.91666667 0.91666667 0.91666667 ... 0.91666667 0.91666667 0.91666667]
 [0.95833333 0.95833333 0.95833333 ... 0.95833333 0.95833333 0.95833333]]


In [60]:
import numpy as np
a=np.array([1, 2, 3, 4])
b=np.array([1, 3, 5, 7])
np.concatenate([b,a])

array([1, 3, 5, 7, 1, 2, 3, 4])

In [61]:
x=[4, 8, 2]
print(np.concatenate([a,b,x]))

[1 2 3 4 1 3 5 7 4 8 2]


In [62]:
grid=np.array([[10,20,30],
              [10,30,50]])

In [63]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[10, 20, 30],
       [10, 30, 50],
       [10, 20, 30],
       [10, 30, 50]])

In [64]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid],axis=1)

array([[10, 20, 30, 10, 20, 30],
       [10, 30, 50, 10, 30, 50]])

In [65]:
a=[1, 3, 5, 7, 1, 2, 3, 4, 8, 9]
a1, a2,a3,a4=np.split(x, [3, 6, 1])
print(a1, a2, a3, a4)

[4 8 2] [] [] [8 2]


In [66]:
grid = np.arange(49).reshape((7,7))
grid

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [67]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 7  8]
 [14 15]
 [21 22]
 [28 29]
 [35 36]
 [42 43]]
[[ 2  3  4  5  6]
 [ 9 10 11 12 13]
 [16 17 18 19 20]
 [23 24 25 26 27]
 [30 31 32 33 34]
 [37 38 39 40 41]
 [44 45 46 47 48]]


In [68]:
x= np.arange(2,10)
print(x)

[2 3 4 5 6 7 8 9]


In [69]:
np.multiply.reduce(x)

362880

In [70]:
np.add.accumulate(x)

array([ 2,  5,  9, 14, 20, 27, 35, 44], dtype=int32)

In [71]:
np.multiply.accumulate(x)

array([     2,      6,     24,    120,    720,   5040,  40320, 362880],
      dtype=int32)